<?php
/**
 * Copyright © Soft Commerce Ltd. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \SoftCommerce\Profile\Block\Adminhtml\Wizard\Steps $block */
?>

<?php
/* @noEscape */ echo $block->getWizardBlock([
    'configurableModal' => $block->getForm() . '.' . $block->getModal()
]);
?>

<?php foreach ($block->getEventHandlerComponents() as $eventHandlerComponent): ?>
    <div data-role="<?= /* @noEscape */ $eventHandlerComponent ?>"></div>
<?php endforeach; ?>

<?php
$dataScope = /* @noEscape */ $block->getData('config/dataScope');
$nameStep = /* @noEscape */ $block->getData('config/nameStepWizard');
$scriptString = <<<script
    require(['jquery', 'uiRegistry', 'underscore'], function ($, registry, _) {
        $('body').trigger('contentUpdated');
        $('.{$dataScope}[data-role=steps-wizard-main]').applyBindings();

        registry.async('{$nameStep}')(function (component) {
            _.delay(component.open.bind(component), 500);
        })
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
