<?php
/**
 * Copyright © Soft Commerce Ltd. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \SoftCommerce\Profile\Block\Adminhtml\Wizard\Steps $block */
?>

<?php
/* @noEscape */ echo $block->getWizardBlock([
    'configurableModal' => $block->getForm() . '.' . $block->getModal()
]);
?>

<?php foreach ($block->getEventHandlerComponents() as $eventHandlerComponent): ?>
    <div data-role="<?= /* @noEscape */ $eventHandlerComponent ?>"></div>
<?php endforeach; ?>

<script>
    require(['jquery', 'uiRegistry', 'underscore'], function ($, registry, _) {
        $('body').trigger('contentUpdated');
        $('.<?= /* @noEscape */ $block->getData('config/dataScope') ?>[data-role=steps-wizard-main]').applyBindings();

        registry.async('<?= /* @noEscape */ $block->getData('config/nameStepWizard') ?>')(function (component) {
            _.delay(component.open.bind(component), 500);
        })
    });
</script>
