<?php
/**
 * Copyright © Soft Commerce Ltd. All rights reserved.
 * See LICENSE.txt for license details.
 */

use SoftCommerce\FreeAgentCore\Block\Adminhtml\System\Config\Form\Field\InitialAuthorisation;

/**
 * @var InitialAuthorisation $block
 * @deprecared
 */
?>
<div class="pp-buttons-container">
    <script>
        require([
            'jquery',
            'prototype',
        ], function($) {
            function function_name() {
                params = {
                };

                console.log('here');

                new Ajax.Request('<?= $block->getButtonUrl() ?>', {
                    loaderArea:     false,
                    asynchronous:   true,
                    parameters:     params,
                    onSuccess: function(transport) {
                        var response = JSON.parse(transport.responseText);
                    }


                });
            }

            $('#app_auth_btn').on('click', function () {
                console.log( $( this ).text() );
                // window.open('<?= $block->getButtonUrl() ?>', 'width=600, height=600');

                //$("#dialog").dialog({modal: true, height: 590, width: 1005 });
                var w = window.open('<?= $block->getButtonUrl() ?>', "popupWindow", "width=600, height=400, scrollbars=yes");
                var $w = $(w.document.body);



                return false;
                function_name ();
            });


            // jQuery('#app_auth_btn').on('click', function () {
                // function_name ();
            // });
        });
    </script>
    <?php echo $block->getButtonHtml() ?>
</div>


