<?php
/**
 * Copyright © Soft Commerce Ltd. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /** @var \FreeAgent\Item\Block\Adminhtml\Profile\Edit\Tab\Export\Product\BeforeGridHtml $block */
?>
<div class="entry-edit form-inline" id="<?= /* @escapeNotVerified */ $block->getId() ?>" data-panel="product-variations">
    <div data-bind="scope: 'profile-steps-wizard'" class="product-create-configuration">
        <div class="product-create-configuration-info">
            <div class="note" data-role="product-create-configuration-info">
                <?= /* @escapeNotVerified */  __('Add products to export list.');?>
            </div>
        </div>
        <div class="product-create-configuration-actions" data-action="product-create-configuration-buttons">
            <div class="product-create-configuration-action" data-bind="scope: 'configurableProductGrid'">
                <?= $block->getAddToExportBtn(); ?>
            </div>
        </div>
    </div>
</div>
