name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.4.4 [CE|EE|ECE 2.4.0-2.4.7] 01 Oct 2024
          tag_name: 1.4.4
          body: |-
            ### softcommerce/module-profile [1.4.4]
            - **Enhancement**: Applied a fix to profile menu items on listing pages.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
