name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.4.3 [CE|EE|ECE 2.4.0-2.4.7] 27 Sep 2024
          tag_name: 1.4.3
          body: |-
            ### softcommerce/module-profile [1.4.3]
            - **Enhancement**: Added profile config data to event dispatcher for save before/after events.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
