name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.4.2 [CE|EE|ECE 2.4.0-2.4.7] 25 Sep 2024
          tag_name: 1.4.2
          body: |-
            ### softcommerce/module-profile [1.4.2]
            - **Enhancement**: Add an option to include a menu with item that depends on URL and confirmation message for profile actions button [#25]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
