name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.4.5 [CE|EE|ECE 2.4.0-2.4.7] 13 Jan 2025
          tag_name: 1.4.5
          body: |-
            ### softcommerce/module-profile [1.4.5]
            - **Enhancement**: Included `servicepoint` type to account for `pakshop` facility.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
